### ISSUE TITLE
Link to the published site

### ISSUE THREAD

**Issue by rosstox26** [gthuiz/MBAnCareerPulse#1]
I see that all your publishable content is in the doc folder. What is the link for me to see the published site? You amy want to add the link to the readme on top.

**Comment by rosstox26** [comment]
It is https://gthuiz.github.io/MBAnCareerPulse/  I imagine.

**Comment by gthuiz** [comment]
Yep thats it!  I'll add it to the README

**Comment by gthuiz** [comment]
Added link to README
